# Generated by Django 3.0.5 on 2020-04-27 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0004_todo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordTodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='トレーニング名')),
                ('times', models.PositiveIntegerField(verbose_name='回数')),
                ('complete_at', models.DateTimeField(null=True, verbose_name='完了日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RECORD_TODO',
                'verbose_name_plural': 'RECORD_TODOs',
                'db_table': 'record_todo',
            },
        ),
    ]
